import {
  Globe,
  Linkedin,
  Instagram,
  Github,
  MessageCircle,
  Mail,
  Phone,
  X,
} from "lucide-react";

export const COUNTRY_CODES = [
  { name: "Jordan", code: "+962", shortcut: "JO", flag: "JO" },
  { name: "Saudi Arabia", code: "+966", shortcut: "SA", flag: "SA" },
  { name: "UAE", code: "+971", shortcut: "AE", flag: "AE" },
  { name: "Qatar", code: "+974", shortcut: "QA", flag: "QA" },
  { name: "Kuwait", code: "+965", shortcut: "KW", flag: "KW" },
  { name: "USA", code: "+1", shortcut: "US", flag: "US" },
  { name: "UK", code: "+44", shortcut: "GB", flag: "GB" },
  { name: "Australia", code: "+61", shortcut: "AU", flag: "AU" },
  { name: "Germany", code: "+49", shortcut: "DE", flag: "DE" },
  { name: "France", code: "+33", shortcut: "FR", flag: "FR" },
  { name: "Italy", code: "+39", shortcut: "IT", flag: "IT" },
  { name: "Spain", code: "+34", shortcut: "ES", flag: "ES" },
  { name: "Netherlands", code: "+31", shortcut: "NL", flag: "NL" },
  { name: "Sweden", code: "+46", shortcut: "SE", flag: "SE" },
  { name: "Norway", code: "+47", shortcut: "NO", flag: "NO" },
  { name: "Denmark", code: "+45", shortcut: "DK", flag: "DK" },
  { name: "Finland", code: "+358", shortcut: "FI", flag: "FI" },
  { name: "Brazil", code: "+55", shortcut: "BR", flag: "BR" },
  { name: "Mexico", code: "+52", shortcut: "MX", flag: "MX" },
  { name: "Argentina", code: "+54", shortcut: "AR", flag: "AR" },
  { name: "South Africa", code: "+27", shortcut: "ZA", flag: "ZA" },
  { name: "India", code: "+91", shortcut: "IN", flag: "IN" },
  { name: "China", code: "+86", shortcut: "CN", flag: "CN" },
  { name: "Japan", code: "+81", shortcut: "JP", flag: "JP" },
  { name: "South Korea", code: "+82", shortcut: "KR", flag: "KR" },
  { name: "Singapore", code: "+65", shortcut: "SG", flag: "SG" },
  { name: "New Zealand", code: "+64", shortcut: "NZ", flag: "NZ" },
  { name: "Russia", code: "+7", shortcut: "RU", flag: "RU" },
  { name: "Turkey", code: "+90", shortcut: "TR", flag: "TR" },
  { name: "Egypt", code: "+20", shortcut: "EG", flag: "EG" },
  { name: "Morocco", code: "+212", shortcut: "MA", flag: "MA" },
  { name: "Nigeria", code: "+234", shortcut: "NG", flag: "NG" },
  { name: "Kenya", code: "+254", shortcut: "KE", flag: "KE" },
  { name: "Pakistan", code: "+92", shortcut: "PK", flag: "PK" },
  { name: "Bangladesh", code: "+880", shortcut: "BD", flag: "BD" },
  { name: "Thailand", code: "+66", shortcut: "TH", flag: "TH" },
  { name: "Vietnam", code: "+84", shortcut: "VN", flag: "VN" },
  { name: "Philippines", code: "+63", shortcut: "PH", flag: "PH" },
  { name: "Malaysia", code: "+60", shortcut: "MY", flag: "MY" },
];

export const SOCIAL_PLATFORMS = [
  {
    key: "website",
    label: "Website",
    placeholder: "https://yoursite.com",
    icon: Globe,
  },
  {
    key: "linkedin",
    label: "LinkedIn",
    placeholder: "Your LinkedIn Username/link",
    icon: Linkedin,
  },
  {
    key: "instagram",
    label: "Instagram",
    placeholder: "Your Instagram Username/link",
    icon: Instagram,
  },
  {
    key: "x",
    label: "X",
    icon: X,
    placeholder: "Your X username or profile URL",
  },
  {
    key: "github",
    label: "GitHub",
    placeholder: "Your GitHub Username/link",
    icon: Github,
  },
  {
    key: "whatsapp",
    label: "WhatsApp",
    placeholder: "Your WhatsApp Number",
    icon: MessageCircle,
  },
  {
    key: "email",
    label: "Email",
    placeholder: "hello@example.com",
    icon: Mail,
  },
  {
    key: "phone",
    label: "Phone",
    placeholder: "+962 7X XXX XXXX",
    icon: Phone,
  },
];
